### ISSUE TITLE
Crafter Terminal Dupe Glitch

### ISSUE THREAD

**Issue by Chydog376** [Ellpeck/PrettyPipes#143]
Hello, I love this mod but I've had one problem with it! But first I would like to mention this is being used in the modpack Create Above and Beyond. The problem is when two players are looking in a crafting terminal and someone requests to pull something into it, if both players try to take it out around the same time, both players will get the item! I don't know if this is becuase of the mod itself of the mod pack but either way I figured its important for both parties to be aware of this issue. This is quite concerning becuase I am a server Admin and short of banning crafting terminals, theres really nothing I can do to prevent this glitch from being used aside from my urging to destroy any items made by it! I hope to see the issue fixed soon and I thank you in advance for your help!

**Comment by Ellpeck** [comment]
Uuuh, this issue should have been fixed in 1.9.6. What version of the mod are you using?

**Comment by Chydog376** [comment]
Oh! I apologise for the bug report then, I am not aware of the exact version but it is apart of the Create Above and Beyond Modpack which hasn't had a significant update in a while due to the extensive modding of mods that they have done! At this point I guess I am just waiting for them to update it then, unfortunetly I don't know if that will come becuase with the way the mod pack words that would be a decent amount of work.

**Comment by aitc-h** [comment]
Just checking the CurseForge page:
[Create Above and Beyond v1.3](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond/files/3567550) is the most recent file.
Checking the manifest, it looks like it's using file ID 3472990.

> `{"projectID":376737,"fileID":3472990,"required":true}`

That matches up with [PrettyPipes-1.9.5.jar](https://www.curseforge.com/minecraft/mc-mods/pretty-pipes/files/3472990).

**Comment by Chydog376** [comment]
Strange I'm still having the problem, I will check my version but I think thats what I have installed!

**Comment by Ellpeck** [comment]
Hi! Can you try to reproduce this issue in the 1.18 or 1.19 versions of the mod? I thought I'd backported the fix, but maybe the original fix also doesn't actually work.

**Comment by Chydog376** [comment]
I can check, I have to get a server running and a friend to test it but I can do that!

**Comment by Chydog376** [comment]
I'm sorry I have been very busy but I havn't forgotten, I will check this soon!
